# Generated by Django 2.2.5 on 2019-09-03 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stationApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listorders',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
