# Generated by Django 2.2.5 on 2019-09-03 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stationApp', '0002_auto_20190904_0214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listorders',
            name='date',
            field=models.DateField(),
        ),
    ]
